    module vtk_generator
    
    use ParticleData
    use MaterialData
    use ElementData
    use FFI, only: iow3
    use constants
    use Simulation
    use, intrinsic :: iso_fortran_env, only: int32, real32

    implicit none

    private :: get_vtk_cell_type
    public :: write_vtk_file


    contains

  subroutine write_vtk_file()
    character(100) :: filename
    integer(int32) :: i, j, unit_num, total_connectivity
    character(len=20) :: str_buffer
    integer(int32) :: vtk_cell_type

    filename = 'output.vtk'
    unit_num = 100
    open(unit=unit_num, file=trim(filename), form='unformatted', access='stream', status='replace', convert='LITTLE_ENDIAN')

    ! Write VTK header
    write(unit_num) '# vtk DataFile Version 3.0'//char(10)
    write(unit_num) 'VTK file generated by Fortran'//char(10)
    write(unit_num) 'BINARY'//char(10)
    write(unit_num) 'DATASET UNSTRUCTURED_GRID'//char(10)

    ! Write points
    write(str_buffer, '(I20)') nb_node
    write(unit_num) 'POINTS '//trim(adjustl(str_buffer))//' float'//char(10)
    write(unit_num) real(Pos, kind=real32)

    ! Calculate total connectivity size
    total_connectivity = sum(element_list%numNodes) + nb_element

    ! Write cells
    write(str_buffer, '(I20)') nb_element
    write(unit_num) 'CELLS '//trim(adjustl(str_buffer))//' '//trim(adjustl(str_buffer))
    write(str_buffer, '(I20)') total_connectivity
    write(unit_num) trim(adjustl(str_buffer))//char(10)
    do i = 1, nb_element
      write(unit_num) int(element_list(i)%numNodes, kind=int32), (int(element_list(i)%nNode(j)-1, kind=int32), j=1,element_list(i)%numNodes)
    end do

    ! Write cell types
    write(str_buffer, '(I20)') nb_element
    write(unit_num) 'CELL_TYPES '//trim(adjustl(str_buffer))//char(10)
    do i = 1, nb_element
      vtk_cell_type = get_vtk_cell_type(element_list(i)%numNodes)
      write(unit_num) int(vtk_cell_type, kind=int32)
    end do

    ! Write point data
    write(str_buffer, '(I20)') nb_node
    write(unit_num) 'POINT_DATA '//trim(adjustl(str_buffer))//char(10)
    write(unit_num) 'SCALARS nodal_data float'//char(10)
    write(unit_num) 'LOOKUP_TABLE default'//char(10)
    write(unit_num) real(Vel(1,:), kind=real32)

    ! Write cell data
    write(str_buffer, '(I20)') nb_element
    write(unit_num) 'CELL_DATA '//trim(adjustl(str_buffer))//char(10)
    write(unit_num) 'SCALARS element_data float'//char(10)
    write(unit_num) 'LOOKUP_TABLE default'//char(10)
    ! write(unit_num) real(history_list%epeff, kind=real32)

    close(unit_num)
  end subroutine write_vtk_file

    function get_vtk_cell_type(num_nodes) result(cell_type)
    integer, intent(in) :: num_nodes
    integer :: cell_type

    select case(num_nodes)
    case(2)
        cell_type = 3  ! VTK_LINE
    case(3)
        cell_type = 5  ! VTK_TRIANGLE
    case(4)
        cell_type = 10 ! VTK_TETRA
    case(8)
        cell_type = 12 ! VTK_HEXAHEDRON
        case default
        cell_type = 7  ! VTK_POLYGON (for any other number of nodes)
    end select
    end function get_vtk_cell_type

    end module vtk_generator